const fileInput=document.querySelector('#file-input'),dropZone=document.querySelector('#drop-zone'),selectedFile=document.querySelector('#selected-file'),privacy=document.querySelector('#privacy-check'),notice=document.querySelector('#notice-check'),analyze=document.querySelector('#analyze-file'),analysisResult=document.querySelector('#analysis-result');
let uploadedFile=null;
function refreshAnalyze(){analyze.disabled=!(uploadedFile&&privacy.checked&&notice.checked)}
function classify(name){const n=name.toLowerCase();if(/기계|냉난방|환기|보일러|공조|급수|배수/.test(n))return{type:'기계설비 유지관리자 선임신고',detail:'기계설비 선임 기준과 신고 서식으로 안내합니다.',href:'#standards',color:'mechanical'};if(/정보통신|통신|네트워크|cctv|홈네트워크|방송/.test(n))return{type:'정보통신설비 유지관리자 선임신고',detail:'정보통신설비 선임 기준과 신고 서식으로 안내합니다.',href:'#calculator',color:'communication'};return{type:'시설관리 문서',detail:'파일명만으로는 유형을 특정하기 어렵습니다. 문서 내용을 확인해 적합한 안내로 연결합니다.',href:'#forms',color:'neutral'}}
function setFile(file){if(!file)return;if(!/\.(pdf|jpg|jpeg|png|hwpx)$/i.test(file.name)){selectedFile.innerHTML='<span class="file-dot error">!</span><span>PDF, JPG, PNG, HWPX 파일만 선택할 수 있습니다.</span>';uploadedFile=null;refreshAnalyze();return}uploadedFile=file;const c=classify(file.name);selectedFile.innerHTML=`<span class="file-dot">✓</span><span><b>${file.name}</b><small>${(file.size/1024).toFixed(1)} KB · ${c.type}으로 분류 예정</small></span>`;analysisResult.innerHTML='';refreshAnalyze()}
fileInput.addEventListener('change',e=>setFile(e.target.files[0]));[privacy,notice].forEach(x=>x.addEventListener('change',refreshAnalyze));['dragenter','dragover'].forEach(t=>dropZone.addEventListener(t,e=>{e.preventDefault();dropZone.classList.add('dragging')}));['dragleave','drop'].forEach(t=>dropZone.addEventListener(t,e=>{e.preventDefault();dropZone.classList.remove('dragging')}));dropZone.addEventListener('drop',e=>setFile(e.dataTransfer.files[0]));
analyze.addEventListener('click',()=>{if(!uploadedFile)return;const c=classify(uploadedFile.name);analysisResult.innerHTML=`<span>✓</span><div><b>자동 분류 결과: ${c.type}</b><p>${c.detail} <a href="${c.href}">관련 기준 확인 →</a></p></div>`;analysisResult.scrollIntoView({behavior:'smooth',block:'nearest'})});
function calculate(){const area=Number(document.querySelector('#area').value);const result=document.querySelector('#calc-result');let title,desc;if(!area||area<0){title='올바른 연면적을 입력해 주세요';desc='0 이상의 숫자를 입력한 후 다시 확인해 주세요.'}else if(area<5000){title='선임 기준 확인 대상 미만입니다';desc='건축물 용도와 예외 규정은 별도 확인이 필요합니다.'}else{const grade=area<15000?'초급 기술자 이상':area<30000?'중급 기술자 이상':area<60000?'고급 기술자 이상':'특급 기술자';title=`${grade} 1명 선임 기준`;desc=`입력 연면적 ${area.toLocaleString()}㎡ 기준입니다. 해당 용도 건축물인지 최종 확인해 주세요.`}result.innerHTML=`<span class="result-icon">i</span><div><b>${title}</b><p>${desc}</p></div>`}document.querySelector('#calculate').addEventListener('click',calculate);
function calculate(){const area=Number(document.querySelector('#area').value);const result=document.querySelector('#calc-result');let title,desc;if(!area||area<0){title='올바른 연면적을 입력해 주세요';desc='0 이상의 숫자를 입력한 후 다시 확인해 주세요.'}else if(area<5000){title='선임 기준 확인 대상 미만입니다';desc='건축물 용도와 예외 규정은 별도 확인이 필요합니다.'}else{const grade=area<15000?'초급 기술자 이상':area<30000?'중급 기술자 이상':area<60000?'고급 기술자 이상':'특급 기술자';title=`${grade} 1명 선임 기준`;desc=`입력 연면적 ${area.toLocaleString()}㎡ 기준입니다. 해당 용도 건축물인지 최종 확인해 주세요.`}result.innerHTML=`<span class="result-icon">i</span><div><b>${title}</b><p>${desc}</p></div>`}document.querySelector('#calculate').addEventListener('click',calculate);
function machineCalculate(){const area=Number(document.querySelector('#machine-area').value),homes=Number(document.querySelector('#households').value),result=document.querySelector('#machine-calc-result');let title,desc;if((!area||area<0)&&(!homes||homes<0)){title='연면적 또는 세대수를 입력해 주세요';desc='비주거 건축물은 연면적, 공동주택은 세대수 기준으로 확인합니다.'}else{const n=Math.max(area>=60000?4:area>=30000?3:area>=15000?2:area>=10000?1:0,homes>=3000?4:homes>=2000?3:homes>=1000?2:homes>=500?1:0);const grade=['선임 기준 확인 대상 미만','책임 초급 1명','책임 중급 1명','책임 고급 1명 · 보조 1명','책임 특급 1명 · 보조 1명'][n];title=grade;desc=n?`입력값 기준입니다. 건축물 용도 및 중앙·지역난방 여부를 최종 확인해 주세요.`:'입력값이 일반 선임 기준 미만입니다. 법령상 별도 대상 여부를 확인해 주세요.'}result.innerHTML=`<span class="result-icon">⚙</span><div><b>${title}</b><p>${desc}</p></div>`}document.querySelector('#machine-calculate').addEventListener('click',machineCalculate);
